right_format = """
"""

format = """
[$shlvl](bg:#FF5555 fg:#FFFFFF)\
[◤](fg:#FF5555 bg:#6666FF)\
[$nix_shell](fg:#FFFFFF bg:#6666FF)\
[◤](fg:#6666FF bg:#DDDD00)\
[ $directory ](bg:#DDDD00 fg:#000000)\
[◤](fg:#DDDD00 bg:#009966)\
[ $git_branch ](bg:#009966 fg:#FFFFFF)\
[◤](fg:#009966)
[ $time ](fg:#FFFFFF bg:#8652AF)\
[◤ ](fg:#8652AF)
"""

[directory]
format = "$path"
truncation_length = 0
truncation_symbol = " "

[git_branch]
symbol = ""
format = '$symbol $branch'

[time]
disabled = false
format = '$time'
time_format = "%T"
utc_time_offset = "+2"

[nix_shell]
disabled = false
symbol = " "
impure_msg = "impure"
pure_msg = "pure"
format = ' $symbol$state ' 

[shlvl]
disabled = false
symbol = "↴ "
format = ' $symbol$shlvl '
