right_format = """
"""

format = """
[  ](fg:#FFFFFF bg:#6666FF)\
[◤](fg:#6666FF bg:#DDDD00)\
$directory\
[◤](fg:#DDDD00 bg:#009966)\
$git_branch\
[◤](fg:#009966)
$time\
[◤ ](fg:#8652AF)
"""
# [  ](fg:#FFFFFF bg:#3030AF)\
# [◤](fg:#3030AF bg:#8652AF)\

[directory]
style = "bg:#DDDD00 fg:#000000"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = " "

[git_branch]
symbol = ""
style = "bg:#009966 fg:#FFFFFF"
format = '[ $symbol $branch ]($style)'

[time]
style = "fg:#FFFFFF bg:#8652AF"
disabled = false
format = '[ $time ]($style)'
time_format = "%T"
utc_time_offset = "+3"
# time_range = "10:00:00-14:00:00"
