# Colors:
# https://coolors.co/palettes/trending

right_format = """
"""

format = """
$cmd_duration
[$shlvl](       fg:#FFFFFF bg:#26547c)\
[](            fg:#26547c bg:#ef476f)\
[$nix_shell](   fg:#FFFFFF bg:#ef476f)\
[](            fg:#ef476f bg:#ffd166)\
[ $directory ]( fg:#000000 bg:#ffd166)\
[](            fg:#ffd166 bg:#06d6a0)\
[$git_branch](  fg:#000000 bg:#06d6a0)\
[](            fg:#06d6a0)
[ ](      fg:#1F231E bg:#fcfcfc)\
[ ](           fg:#fcfcfc)
"""

[directory]
format = "$path"
truncation_length = 0
truncation_symbol = " "

[git_branch]
symbol = ""
format = ' $symbol $branch '

[time]
disabled = false
format = '$time'
time_format = "%T"
utc_time_offset = "+2"

[nix_shell]
disabled = false
symbol = " "
impure_msg = "impure"
pure_msg = "pure"
format = ' $symbol$state ' 

[shlvl]
disabled = false
symbol = "↴ "
format = ' $symbol$shlvl '
threshold = 3
