right_format = """
"""

format = """
$shlvl\
[◤](fg:#FF5555 bg:#6666FF)\
$nix_shell\
[◤](fg:#6666FF bg:#DDDD00)\
$directory\
[◤](fg:#DDDD00 bg:#009966)\
$git_branch\
[◤](fg:#009966)
$time\
[◤ ](fg:#8652AF)
"""

[directory]
style = "bg:#DDDD00 fg:#000000"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = " "

[git_branch]
symbol = ""
style = "bg:#009966 fg:#FFFFFF"
format = '[ $symbol $branch ]($style)'

[time]
style = "fg:#FFFFFF bg:#8652AF"
disabled = false
format = '[ $time ]($style)'
time_format = "%T"
utc_time_offset = "+3"
# time_range = "10:00:00-14:00:00"

[nix_shell]
disabled = false
symbol = " "
impure_msg = "impure"
pure_msg = "pure"
style = "fg:#FFFFFF bg:#6666FF"
format = '[ $symbol$state ]($style)' 

[shlvl]
disabled = false
symbol = "↴ "
style = "bg:#FF5555 fg:#FFFFFF"
format = '[ $symbol$shlvl ]($style)'
