right_format = """
"""

format = """
[$shlvl](       fg:#FFFFFF bg:#FF5555)\
[◤](            fg:#FF5555 bg:#6666FF)\
[$nix_shell](   fg:#FFFFFF bg:#6666FF)\
[◤](            fg:#6666FF bg:#DDDD00)\
[ $directory ]( fg:#000000 bg:#DDDD00)\
[◤](            fg:#DDDD00 bg:#009966)\
[ $git_branch ](fg:#FFFFFF bg:#009966)\
[◤](            fg:#009966)
[ $time ](      fg:#FFFFFF bg:#8652AF)\
[◤ ](           fg:#8652AF)
"""

[directory]
format = "$path"
truncation_length = 0
truncation_symbol = " "

[git_branch]
symbol = ""
format = '$symbol $branch'

[time]
disabled = false
format = '$time'
time_format = "%T"
utc_time_offset = "+2"

[nix_shell]
disabled = false
symbol = " "
impure_msg = "impure"
pure_msg = "pure"
format = ' $symbol$state ' 

[shlvl]
disabled = false
symbol = "↴ "
format = ' $symbol$shlvl '
